lib/hbits_web/router.ex
defmodule HbitsWeb.Router do
  use HbitsWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router,
  extensions: [PowResetPassword, PowEmailConfirmation]
  import Phoenix.LiveView.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :liveview do
    plug :put_root_layout, {HbitsWeb.LayoutView, :app}
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser
    pow_routes
    pow_extension_routes
  end

  scope "/", HbitsWeb do
    pipe_through [:browser, :protected]
    resources "/habits", HabitController
    get "/", PageController, :index
  end

  scope "/", HbitsWeb do
    pipe_through [:browser, :protected, :liveview]
    resources "/habits", HbitController, only: [:show] do
      live "/calendar", CalendarLive
    end
  end


  # Other scopes may use custom stacks.
  # scope "/api", HbitsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: HbitsWeb.Telemetry
    end
  end
end

lib/hbits_web/views/layout_view.ex
defmodule HbitsWeb.LayoutView do
  use HbitsWeb, :view
end

lib/hbits_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Hbits</title>
    <link href="https://fonts.googleapis.com/css2?family=Karla:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/styles/app.css") %>"/>
    <%= csrf_meta_tag() %>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header class="mb-small">
      <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="<%= Routes.page_path(@conn, :index) %>">
          <img src="<%= Routes.static_path(@conn, "/images/logo.svg") %>" width="140" class="d-inline-block align-top" alt="logo hbits" loading="lazy">
        </a>
        <div>
          <%= if Pow.Plug.current_user(@conn) do %>
            <span><%= link "Habitos", to: Routes.habit_path(@conn, :index), class: "btn btn-secondary" %></span>
            <span><%= link "Salir", to: Routes.pow_session_path(@conn, :delete), method: :delete, class: "btn btn-primary" %></span>
          <% else %>
            <span><%= link "Registrarse", to: Routes.pow_registration_path(@conn, :new), class: "btn btn-primary" %></span>
            <span><%= link "Entrar", to: Routes.pow_session_path(@conn, :new), class: "btn btn-success" %></span>
          <% end %>
        </div>
      </nav>
    </header>
    
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
    <footer class="mt-5">
      <p class="text-center">Copyright ®Hbits</p>
    </footer>
  </body>
</html>